version: '3'

# uffizzi integration
x-uffizzi:
  ingress:
    service: dashboard
    port: 4040

services:

    mongo:
        image: mongo
        volumes:
            - ./data-db:/data/db
        deploy:
          resources:
            limits:
              memory: 2000M

    parse:
        image: "${PARSE_SERVER_IMAGE}"
        environment:
            - PARSE_SERVER_APPLICATION_ID=yourappid
            - PARSE_SERVER_MASTER_KEY=yourmasterkey
            - PARSE_SERVER_DATABASE_URI=mongodb://mongo:27017/dev
            - PARSE_SERVER_START_LIVE_QUERY_SERVER=1
            - PARSE_SERVER_LIVE_QUERY={"classNames":["people","monitor"]}
        deploy:
          resources:
            limits:
              memory: 2000M
        # entrypoint: ["/bin/sh", "-c", "sleep 5;  node ./bin/parse-server"]

    dashboard:
        image: parseplatform/parse-dashboard
        environment:
            - PARSE_DASHBOARD_SERVER_URL=http://localhost:1337/parse
            - PARSE_DASHBOARD_APP_ID=yourappid
            - PARSE_DASHBOARD_MASTER_KEY=yourmasterkey
            - PARSE_DASHBOARD_APP_NAME=MyApp
            - PARSE_DASHBOARD_ALLOW_INSECURE_HTTP=1
            - PARSE_DASHBOARD_USER_ID=user
            - PARSE_DASHBOARD_USER_PASSWORD=pass
        deploy:
          resources:
            limits:
              memory: 250M

# networks:
#   parse_network:
#     driver: bridge
