version: '3'

# uffizzi integration
x-uffizzi:
  ingress:
    service: nginx
    port: 8081

services:

  postgres:
      image: postgres
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=password
        - POSTGRES_DB=postgres
      deploy:
            resources:
              limits:
                memory: 1000M
      volumes:
        - postgres_data:/var/lib/postgresql

  parse:
        image: "${PARSE_SERVER_IMAGE}"
        environment:
        - PARSE_SERVER_APPLICATION_ID=parse
        - PARSE_SERVER_MASTER_KEY=parse@master123!
        - PARSE_SERVER_DATABASE_URI=postgresql://postgres:password@localhost:5432/postgres
        - PARSE_SERVER_MOUNT_PATH=/parse
        deploy:
          resources:
            limits:
              memory: 1000M
  parse-dashboard:
        image: parseplatform/parse-dashboard
        environment:
        - PARSE_DASHBOARD_ALLOW_INSECURE_HTTP=true
        # - PARSE_DASHBOARD_COOKIE_SESSION_SECRET=AB8849B6-D725-4A75-AA73-AB7103F0363F
        - PARSE_DASHBOARD_SERVER_URL=/parse
        - MOUNT_PATH=/dashboard
        volumes:
        -  ./dashboard/parse-dashboard-config.json:/src/Parse-Dashboard/parse-dashboard-config.json
        command: parse-dashboard --dev"
        deploy:
          resources:
            limits:
              memory: 500M

  nginx:
    image: nginx:alpine
    volumes:
    - ./nginx:/etc/nginx

volumes:
  postgres_data:
